services:
  pgvector:
    image: agnohq/pgvector:16
    container_name: pgvector
    restart: always
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=ai
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data

volumes:
  pgvolume:
    driver: local
